kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: example-service-secret
  annotations:
    avp.kubernetes.io/path: "nonprod-secret" # The name of your AWS Secret
data:
  IBM_API_KEY: <WATSON_X_IBM_API_KEY | base64encode>
  WATSON_X_PROJECT_ID: <WATSON_X_PROJECT_ID | base64encode>

